// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtLJOGtwJV7IcXBuPFv1tnxuuDV-mTnzU',
    appId: '1:819254153590:web:7c305681944ea0cbb5ea57',
    messagingSenderId: '819254153590',
    projectId: 'project-4315590107491761939',
    authDomain: 'project-4315590107491761939.firebaseapp.com',
    storageBucket: 'project-4315590107491761939.firebasestorage.app',
    measurementId: 'G-PGKRRB3GN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0bxcjuNVa-DDjat7PKqAMzZCESl5Y04s',
    appId: '1:819254153590:android:adcff5b2ffbe5cc6b5ea57',
    messagingSenderId: '819254153590',
    projectId: 'project-4315590107491761939',
    storageBucket: 'project-4315590107491761939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQPhYgWitLujlL4s0hcEXlMdyZjBZW2o4',
    appId: '1:819254153590:ios:b7dccd3ab9fbe62db5ea57',
    messagingSenderId: '819254153590',
    projectId: 'project-4315590107491761939',
    storageBucket: 'project-4315590107491761939.firebasestorage.app',
    iosBundleId: 'com.example.bt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQPhYgWitLujlL4s0hcEXlMdyZjBZW2o4',
    appId: '1:819254153590:ios:b7dccd3ab9fbe62db5ea57',
    messagingSenderId: '819254153590',
    projectId: 'project-4315590107491761939',
    storageBucket: 'project-4315590107491761939.firebasestorage.app',
    iosBundleId: 'com.example.bt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtLJOGtwJV7IcXBuPFv1tnxuuDV-mTnzU',
    appId: '1:819254153590:web:cc7be92bbbd9c33bb5ea57',
    messagingSenderId: '819254153590',
    projectId: 'project-4315590107491761939',
    authDomain: 'project-4315590107491761939.firebaseapp.com',
    storageBucket: 'project-4315590107491761939.firebasestorage.app',
    measurementId: 'G-2LJG7BMHWN',
  );
}
