// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBhiWQOZQlfiQhXyIjNMugir1FJuuV-Nw',
    appId: '1:652686606178:web:235b5844fa2fcee757f63b',
    messagingSenderId: '652686606178',
    projectId: 'btvn242025',
    authDomain: 'btvn242025.firebaseapp.com',
    storageBucket: 'btvn242025.firebasestorage.app',
    measurementId: 'G-XBDDFQVR77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDywZHUJelp7yJjR5ts3iIiSpHoxGNhgW8',
    appId: '1:652686606178:android:e203b3e6ce5c2a0f57f63b',
    messagingSenderId: '652686606178',
    projectId: 'btvn242025',
    storageBucket: 'btvn242025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo-6uyGj14AI0ZoVJ4VPCPkECGpVOGqT0',
    appId: '1:652686606178:ios:1b61c1cc327b08c657f63b',
    messagingSenderId: '652686606178',
    projectId: 'btvn242025',
    storageBucket: 'btvn242025.firebasestorage.app',
    iosBundleId: 'com.example.btvn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo-6uyGj14AI0ZoVJ4VPCPkECGpVOGqT0',
    appId: '1:652686606178:ios:1b61c1cc327b08c657f63b',
    messagingSenderId: '652686606178',
    projectId: 'btvn242025',
    storageBucket: 'btvn242025.firebasestorage.app',
    iosBundleId: 'com.example.btvn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBhiWQOZQlfiQhXyIjNMugir1FJuuV-Nw',
    appId: '1:652686606178:web:a8e2f167397c2c5457f63b',
    messagingSenderId: '652686606178',
    projectId: 'btvn242025',
    authDomain: 'btvn242025.firebaseapp.com',
    storageBucket: 'btvn242025.firebasestorage.app',
    measurementId: 'G-ZYZ2YH43DL',
  );

}