// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC1j_uwxM2ai2SzV3auWUaQQ560XxtWxU',
    appId: '1:49771951144:web:7b6ac089ae3df9304d711d',
    messagingSenderId: '49771951144',
    projectId: 'btvn1512024',
    authDomain: 'btvn1512024.firebaseapp.com',
    storageBucket: 'btvn1512024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAYdDOo-EshlUCPzDFP3FjPeLiwgvSUvk',
    appId: '1:49771951144:android:99a3a158dd324b244d711d',
    messagingSenderId: '49771951144',
    projectId: 'btvn1512024',
    storageBucket: 'btvn1512024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXBXwittuoDwThzrvj6qLaaRcpI1AmsAs',
    appId: '1:49771951144:ios:5b2cb5e875b9ee984d711d',
    messagingSenderId: '49771951144',
    projectId: 'btvn1512024',
    storageBucket: 'btvn1512024.firebasestorage.app',
    iosBundleId: 'com.example.buoi3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXBXwittuoDwThzrvj6qLaaRcpI1AmsAs',
    appId: '1:49771951144:ios:5b2cb5e875b9ee984d711d',
    messagingSenderId: '49771951144',
    projectId: 'btvn1512024',
    storageBucket: 'btvn1512024.firebasestorage.app',
    iosBundleId: 'com.example.buoi3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC1j_uwxM2ai2SzV3auWUaQQ560XxtWxU',
    appId: '1:49771951144:web:3cab744ef1afdb894d711d',
    messagingSenderId: '49771951144',
    projectId: 'btvn1512024',
    authDomain: 'btvn1512024.firebaseapp.com',
    storageBucket: 'btvn1512024.firebasestorage.app',
  );
}
