// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6w9GUFFnK4_YFzcx8V7qOtXixmOo68pw',
    appId: '1:1052617822196:web:13fcc9f202b503fb96f3a1',
    messagingSenderId: '1052617822196',
    projectId: 'crudtotial',
    authDomain: 'crudtotial.firebaseapp.com',
    storageBucket: 'crudtotial.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmUMW-x0LryFqvYHEPUfYzwwcr_6CIwgI',
    appId: '1:1052617822196:android:b606db231b07c0d796f3a1',
    messagingSenderId: '1052617822196',
    projectId: 'crudtotial',
    storageBucket: 'crudtotial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5UlgJcBWRM0hI5xkKj63PfhgFyxFG2DU',
    appId: '1:1052617822196:ios:a7d1d5537bd3add996f3a1',
    messagingSenderId: '1052617822196',
    projectId: 'crudtotial',
    storageBucket: 'crudtotial.firebasestorage.app',
    androidClientId: '1052617822196-cs094kefjjtdotc9mumpt5h8jkuv6jcs.apps.googleusercontent.com',
    iosClientId: '1052617822196-opi8tmsf7mv8p4n6ks41pm5b2u5b2t5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.bt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5UlgJcBWRM0hI5xkKj63PfhgFyxFG2DU',
    appId: '1:1052617822196:ios:a7d1d5537bd3add996f3a1',
    messagingSenderId: '1052617822196',
    projectId: 'crudtotial',
    storageBucket: 'crudtotial.firebasestorage.app',
    androidClientId: '1052617822196-cs094kefjjtdotc9mumpt5h8jkuv6jcs.apps.googleusercontent.com',
    iosClientId: '1052617822196-opi8tmsf7mv8p4n6ks41pm5b2u5b2t5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.bt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6w9GUFFnK4_YFzcx8V7qOtXixmOo68pw',
    appId: '1:1052617822196:web:27264129a0d3e49896f3a1',
    messagingSenderId: '1052617822196',
    projectId: 'crudtotial',
    authDomain: 'crudtotial.firebaseapp.com',
    storageBucket: 'crudtotial.firebasestorage.app',
  );
}
